# Generated by Django 4.0.2 on 2022-02-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_studentdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentData',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='isStu',
        ),
    ]
