# Generated by Django 4.0.1 on 2022-04-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_problems_isvoted_alter_contactform_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='isvoted',
        ),
        migrations.AddField(
            model_name='signup',
            name='isvoted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
