# Generated by Django 4.0.2 on 2022-02-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='isappoved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
