# Generated by Django 4.0.2 on 2022-02-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_problems_isappoved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='problem',
            field=models.CharField(max_length=30),
        ),
    ]
