# Generated by Django 4.0.1 on 2022-04-01 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_problems_isvoted_signup_isvoted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='isvoted',
        ),
    ]
