# Generated by Django 4.0.1 on 2022-04-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_signup_isvoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='isvoted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
